matsadler/magnus

- README.md
> Add github-flavored markdown syntax highlighting to README

- build.rs
Fixes that Magnus’s bindings are generated when `rb-sys` is in use.
> build.rs: correct `rb-sys-interop` feature detection

- src/error.rs
Passing the message directly allows the good old [Format string attack](https://owasp.org/www-community/attacks/Format_string_attack) (and makes it really hard to print errors in my liquid parser, famously rich in '%' characters!)
> rb_raise takes a printf-style % format string:

- Cargo.lock
- Cargo.toml
- Gemfile
- README.md
- examples/custom_exception_ruby/ext/ahriman/Cargo.lock
- examples/custom_exception_rust/ext/ahriman/Cargo.lock
- examples/rust_blank/ext/rust_blank/Cargo.lock
- src/lib.rs
In https://github.com/oxidize-rb/rb-sys/pull/94, I changed the strategy for how rb-sys detects if it should build for usage in a gem. It relies on the create_rust_makefile setting `--cfg=rb_sys_gem` in the `$RUSTFLAGS`. This strategy makes it so magnus no longer needs to worry about anything when a Gem is being built, which should solve some integration headaches.
As such, we no longer need to conditionally do things like setting the ruby_abi_version, since that is now now handled automatically.
Another result of this PR is that the minimum version of `rb-sys` is now `0.9.37` is now available, which [adds detection for Ruby autoconf variables (like `DEP_RB_DEFINES_USE_FLONUM`)](https://github.com/oxidize-rb/rb-sys/pull/93).
> Rely on `rb-sys` for gem compilation awareness

- .cargo/config.toml
- .github/workflows/test.yaml
- .gitignore
- Cargo.lock
- Cargo.toml
- Gemfile
- README.md
- examples/custom_exception_ruby/ext/ahriman/Cargo.lock
- examples/custom_exception_rust/ext/ahriman/Cargo.lock
- examples/rust_blank/ext/rust_blank/Cargo.lock
- src/gc.rs
Ruby 3.2 will be adding support for mswin builds (which uses `msvc` toolchain rather than `mingq`). We already support this in rb-sys, and the setup-ruby-and-ruby GitHub action. This PR adds official support for magnus.
depends on #25
> Add `mswin` support

- Cargo.lock
- Cargo.toml
- Gemfile
- README.md
- build.rs
- examples/custom_exception_ruby/ext/ahriman/Cargo.lock
- examples/custom_exception_rust/ext/ahriman/Cargo.lock
- examples/rust_blank/ext/rust_blank/Cargo.lock
- src/float.rs
- src/lib.rs
- src/r_float.rs
- src/try_convert.rs
- src/value.rs
- src/value/flonum.rs
This PR makes magnus work when `USE_FLONUM=0`. I've verified this compiling Ruby with `CPPFLAGS="-DUSE_FLONUM=0"`, and things are working.
As part of this work, there are a number of integration issues that [I fixed by introducing a `rb-sys-env` crate](https://github.com/oxidize-rb/rb-sys/pull/99). Incidentally, this [fixes cross-compilation issues for `x64-mingw32` and `x64-mingw32-ucrt`](https://github.com/bytecodealliance/wasmtime-rb/actions/runs/3448763186/jobs/5756065948).
> Add support for rubies compiled with `USE_FLONUM=0`, fix `mingw` cross-compilation

- .github/workflows/test.yaml
GitHub actions runner induced a breaking change, but I fixed in https://github.com/oxidize-rb/actions/commit/27945b582cd8f0e17392e8d0690012979923777e
> Re-enable `mswin` builds

- src/gc.rs
When trying to use `gc::mark_slice`, I realized that the last element of the slice never gets marked. This is [how `gc_mark_locations` is implemented in Ruby 3.1](https://github.com/ruby/ruby/blob/4491bb740a9506d76391ac44bb2fe6e483fec952/gc.c#L6180-L6188):
```c
static void
gc_mark_locations(rb_objspace_t *objspace, const VALUE *start, const VALUE *end, void (*cb)(rb_objspace_t *, VALUE))
{
long n;
if (end <= start) return;
n = end - start;
each_location(objspace, start, n, cb);
}
```
It marks `n` VALUEs, where `n = end-start`. By sending the first and the last VALUEs of the slice, `n` ends up `slice.len() - 1`, omitting the last element.
~I'm fixing this by throwing a +1 on the last element. I don't know if that's the most idiomatic fix, but worked when I tried it in wasmtime-rb.~ Updated …
> Make `gc::mark_slice` mark the entire slice

- CHANGELOG.md
- magnus-macros/src/typed_data.rs
- src/class.rs
- src/lib.rs
- src/typed_data.rs
Starting with Ruby 3.2, leaving the default allocator function for `T_DATA` will emit a warning:
> warning: undefining the allocator of T_DATA class [...]
This commit adds `RClass::undef_alloc_func` so that users can get rid of that warning.
Given any `T_DATA` will trigger the warning, I think it'd make sense for this to be in the examples and in [the macro implementation](https://github.com/matsadler/magnus/blob/ae792419bed70107d4c930e1f8193272750b9fd2/magnus-macros/src/typed_data.rs#L134-L137). Agreed? If so, happy to create another PR for that.
----
Relevant references:
- [Code in ruby/ruby where this warning is emitted](https://github.com/ruby/ruby/blob/91050d3443956a2841aa91defee0d178a18fc347/gc.c#L3100-L3103)
- [Issue on Ruby's issue tracker](https://bugs.ruby-lang.org/issues/18007)
> Implement `rb_undef_alloc_func`

- CHANGELOG.md
- src/value.rs
Allow calling a method only if it’s public, returning an error if it’s private or protected.
> Add `Value::funcall_public`

- CHANGELOG.md
- src/error.rs
Shorthand for `std::result::Result<T, Error>`. I haven't updated existing instances of `Result<_, Error>` in the library except where necessary.
> Add `error::Result<T>`

- src/typed_data.rs
If there is no mark function, then we assume there are no references to Ruby objects. As such, we can avoid inserting GC write barriers.
See: https://github.com/ruby/ruby/pull/7255
> Default `TypedData` as `wb_protected` when there is no mark function

- Cargo.lock
- Cargo.toml
- README.md
- src/r_string.rs
- src/try_convert.rs
- tests/bytes.rs
i Added support for converting a ruby String into a rust byte collection
In ruby the main way to represent some bytes is with a string, (see File.read or Base64.strict_decode64). and the current way to accept such
a string with magnus is by receiving a RString and calling `.as\_slice().as\_vec()` which is unsafe, this creates safe interface to receive bytes from ruby.
I've decided to use the Bytes crate since it seems to be rust communty's prefered way of dealing with collections of bytes and made the inclusion of it a non defaulted feature
> add ruby String to rust Byte Collection conversion

- src/r_string.rs
> Fix a typo in the deprecated message

- src/method.rs
- tests/bytes.rs
Without this change, I would get the following warning when running `cargo test`
```
warning: unused imports: `RString`, `eval`
--> tests/bytes.rs:1:14
|
1 | use magnus::{eval, RString};
|              ^^^^  ^^^^^^^
|
= note: `#[warn(unused_imports)]` on by default
warning: `magnus` (test "bytes") generated 1 warning
```
The `use` was only needed when the "bytes-crate" feature is enabled, so I moved the `use` statement inside the feature conditional function that uses it.
---
I've also included an unrelated commit that fixes a typo in a comment.
> Fix unused import warning

- src/block.rs
- src/class.rs
- src/exception.rs
- src/into_value.rs
- src/lib.rs
- src/value.rs
This PR adds support for function calls and object initialization with keyword arguments.
The trait `KwArgList` is quite similar to `ArgList`, with the key difference being an additional `contains_kw_args` method indicating if the final value in the slice is an `RHash` intended for use as kwargs. I only implemented it for `RHash`. It should be possible to implement for the value arrays and tuples that `ArgList` is implemented for, but it isn't obvious to me how to distinguish between, for example, a `[Value; 3]` where the final element is an `RHash` intended to be used as kwargs and a `[Value; 3]` where that is not the case.
> Add `funcall_kw` and `new_instance_kw` methods

- src/into_value.rs
> Fix typo in `ArgList::contains_kw_args` docs

- Cargo.lock
- Cargo.toml
- examples/complete_object/ext/temperature/Cargo.lock
- examples/complete_object/ext/temperature/Cargo.toml
- examples/custom_exception_ruby/ext/ahriman/Cargo.lock
- examples/custom_exception_ruby/ext/ahriman/Cargo.toml
- examples/custom_exception_rust/ext/ahriman/Cargo.lock
- examples/custom_exception_rust/ext/ahriman/Cargo.toml
- examples/rust_blank/ext/rust_blank/Cargo.lock
- examples/rust_blank/ext/rust_blank/Cargo.toml
- src/r_array.rs
- src/r_string.rs
This PR implements the stable API provided by rb-sys such that magnus remains compatible with ruby-head in the event of struct layout changes.
> Implement rb-sys stable api for RArray and RString

- src/r_array.rs
> Implement `IntoValueFromNative` for `Vec`

- CHANGELOG.md
- Cargo.lock
- Cargo.toml
- README.md
- src/time.rs
- tests/time.rs
Draft PR to add support for converting to and from `chrono::DateTime<Utc>` and `chrono::DateTime<FixedOffset>` timestamps.  [Related discussion](https://github.com/matsadler/magnus/issues/113).  I'm out of my depth here both with respect to the Ruby C API and with respect to usage of `chrono`, so additional diligence might be needed.
I am not attached to this PR at all.  With support for nanosecond precision recently added (still to be tested on our side), it is possible that we will not need `chrono`.
> Add support for chrono::DateTime<T>

- src/time.rs
- tests/time.rs
A [recent PR](https://github.com/matsadler/magnus/pull/114) added support for converting to and from `chrono::DateTime<Utc>` and `chrono::DateTime<FixedOffset>`.  This PR does the following:
* Allow times before the epoch (1970).
* Fix a bug in which Ruby `Time` objects are created in the system's local timezone rather than the timezone of the `chrono` datetime.
Due to my lack of knowledge, I have resorted to going through `funcall`, but I suspect there's a way to do this more efficiently through C API.
> Fixes for IntoValue for chrono::DateTime<Utc> and chrono::DateTime<FixedOffset>

- src/try_convert.rs
This PR adds support for [NonZero](https://doc.rust-lang.org/std/num/struct.NonZero.html) types, which is part of `std::num`.
I tried using `NonZero<T>`, but `ZeroablePrimitive` is a nightly trait, so used a macro instead. It raises an `ArgumentError` if the value is zero, but I think a `TypeError` would work as well.
Edit: Switched to `NonZeroI8`, `NonZeroI16`, etc. since `NonZero<T>` is not available in 1.61.
> Add `TryConvert` for `NonZero` types

- README.md
- examples/mut_point.rs
- magnus-macros/src/lib.rs
- src/typed_data.rs
- tests/time.rs
Fixes #123
I took our conversations as input to update the README with new example.
Then I also updated the examples as well as inline documentations in the macro.
I fixed a few other problems:
- deprecated usage
- doctests if they went wrong
> Update wrap and TypedData documentation

- src/method.rs
Currently, Magnus compiles methods and functions with an arity of 16, but when the extension is loaded in Ruby, it errors with:
```text
lib/ruby/3.4.0/bundled_gems.rb:82:in 'Kernel.require': arity out of range: 16 for -2..15 (ArgumentError)
```
> Fix max arity for methods and functions

- src/r_hash.rs
- src/try_convert.rs
- tests/hash.rs
Adds support for `std::collections::BTreeMap`
> Add conversion for BTreeMap

- README.md
Thanks so much for this awesome project! It was really helpful for me to leverage a library in Rust and then create a Ruby gem for it. I pieced together many things from examples and digging deep into the source code for magnus, halton, rbsys, and other stuff to figure out how to:
* build a gem
* for different architectures
* with type hints
* cross-compiled and published with a GitHub action
It was tricky to get all of the details just right (for example, as a Ruby novice, I wasn't even sure if I needed to or how to publish the gem for different operating systems), and to be honest, maybe I could still use some tweaks to my [gemspec](https://github.com/juharris/optify/blob/main/ruby/optify/optify.gemspec) or Rakefile. I think my repo, optify, is very complete example of how to use …
> [README] Add link to optify as an example

- Cargo.lock
- Cargo.toml
- examples/complete_object/ext/temperature/Cargo.lock
- examples/custom_exception_ruby/ext/ahriman/Cargo.lock
- examples/custom_exception_rust/ext/ahriman/Cargo.lock
- examples/rust_blank/ext/rust_blank/Cargo.lock
- src/r_typed_data.rs
- src/typed_data.rs
In Ruby 3.5, the RTypedData struct definition was [modified to optimize its size](https://github.com/ruby/ruby/pull/13190), which broke ruby-head builds for apps using magnus gems. To address this, I implemented stable API support for the necessary features in [#530](https://github.com/oxidize-rb/rb-sys/pull/530), ensuring that ruby-head is now compatible.
Also, I took the opportunity to optimize `TypedData::deref` with the new `RTYPEDDATA_GET_DATA` macro to avoid an extra libruby call
> Use stable rb-sys macros for `RTypedData` stuff

- .github/workflows/test.yaml
- README.md
- src/lib.rs
I don't expect anything go wrong with 3.4. So adding tests in CI.
These symbols are removed from 3.4. magnus will never implement them so I removed them too.
// * `RB_NEWOBJ`:
// * `rb_newobj`:
// * `RB_NEWOBJ_OF`:
// * `rb_newobj_of`:
https://www.ruby-lang.org/en/news/2024/12/25/ruby-3-4-0-released/
> Test Ruby 3.4 in CI

- src/r_string.rs
- tests/string.rs
I noticed after trying to update a library to Magnus 0.8.1 that the error message that's emitted when a string contains an invalid byte sequence changed. For example, if I have a Ruby string that looks like `"\xFF\xFF"` and try to convert it to a Rust string, I get the error message `#<EncodingError: expected utf-8, got UTF-8 (param at index 0)>` instead of an error message saying the string contains an invalid byte sequence.
After looking at the code, I think the conditional in `as_str_unconstrained` should be inverted so the message for an unexpected encoding error is emitted for non-UTF-8 strings and the invalid byte sequence error is emitted if the string is UTF-8 but contains an invalid byte sequence.
> Fix error message when there's an invalid byte sequence
